# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import reverseproxy_pb2 as reverseproxy__pb2


class TriggerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/trigger.Trigger/Register',
                request_serializer=reverseproxy__pb2.Profile.SerializeToString,
                response_deserializer=reverseproxy__pb2.Profile.FromString,
                )
        self.Fire = channel.stream_stream(
                '/trigger.Trigger/Fire',
                request_serializer=reverseproxy__pb2.Reply.SerializeToString,
                response_deserializer=reverseproxy__pb2.Request.FromString,
                )


class TriggerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fire(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TriggerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=reverseproxy__pb2.Profile.FromString,
                    response_serializer=reverseproxy__pb2.Profile.SerializeToString,
            ),
            'Fire': grpc.stream_stream_rpc_method_handler(
                    servicer.Fire,
                    request_deserializer=reverseproxy__pb2.Reply.FromString,
                    response_serializer=reverseproxy__pb2.Request.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trigger.Trigger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Trigger(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trigger.Trigger/Register',
            reverseproxy__pb2.Profile.SerializeToString,
            reverseproxy__pb2.Profile.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Fire(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/trigger.Trigger/Fire',
            reverseproxy__pb2.Reply.SerializeToString,
            reverseproxy__pb2.Request.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
